#!/usr/bin/env bash

set -Cue -o pipefail

PROJECT_DIR="$(cd "$(dirname "${0}")/.." ; pwd)" # Absolute path to project

(
  cd "${PROJECT_DIR}/tests"

  python3 -m unittest discover \
    -p *_tests.py
)
