#!/usr/bin/env bash

set -Cue -o pipefail

# Wrapper that sources the sash script
# This is used to access the library functions of sash

PROJECT_DIR="$(cd "$(dirname "${0}")/.." ; pwd)" # Absolute path to project

(
  cd "$PROJECT_DIR"

  . sash

  "$@"
)
