name: pipeline
on: [push]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: checks
        run: make check
      - name: tests
        run: make test
